### ISSUE TITLE
File not downloading

### ISSUE THREAD

**Issue by ghost** [NoWorries/chrome-figma-ui-mod#21] opened 2023-12-13 15:54 UTC
I have the Figma Library analytics modal visible, and the extension installed, I press the export CSV button, but nothing happens.
The first time I tried it, it worked like a charm and I love this extension. 
But after updating Mac Chrome Version 120.0.6099.109 (Official Build) (arm64) nothing seems to work.

I have tried the Toggle UI option, no change.

**Comment by NoWorries** [comment] 2024-01-24 00:07
How are you launching the DS Analytics modal? Can you tell me from which page/menu you launch it.

I believe there are a couple ways to launch it now and the plugins JS targeting might need an update to make sure it can work with the latest classnames. 

And if Figma updates any classnames it will also break, so have to monitor for issues. Thanks for reporting!

**Comment by NoWorries** [comment] 2024-01-24 00:08
This other issues addressed the two paths for launching analytics. Can you let me know if this is the same experience you are having?

https://github.com/NoWorries/chrome-figma-ui-mod/issues/20

**Comment by NoWorries** [comment] 2024-03-23 05:48
Closing this, unable to reproduce problem.

**Closed as completed** 2024-03-23 05:48 UTC
